title: Diary of a PhD student in Aotearoa
author: Lucy de Jong
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  So this description is for the document head meta which feeds into google search results and in feed.xml site description (what is that?)
  I guess the description is that I'm beginning my PhD journey on New Zealand soil, during a pandemic, and I want to get down my thoughts/feelings/emotions 
  and help pages for myself in the future!

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  lucy924 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
